<?php

declare(strict_types=1);

namespace PHPStreamServer\Plugin\HttpServer\Internal;

/**
 * @internal
 */
final class MimeTypeMapper
{
    private const MIME_TYPES_MAP = [
        'html' => 'text/html',
        'htm' => 'text/html',
        'css' => 'text/css',
        'csv' => 'text/csv',
        'ics' => 'text/calendar',
        'js' => 'text/javascript',
        'mjs' => 'text/javascript',
        'md' => 'text/markdown',
        'markdown' => 'text/markdown',
        'mml' => 'text/mathml',
        'txt' => 'text/plain',
        'vcf' => 'text/vcard',
        'vtt' => 'text/vtt',
        'apng' => 'image/apng',
        'avif' => 'image/avif',
        'gif' => 'image/gif',
        'heic' => 'image/heic',
        'heif' => 'image/heif',
        'jpeg' => 'image/jpeg',
        'jpg' => 'image/jpeg',
        'jxl' => 'image/jxl',
        'png' => 'image/png',
        'svg' => 'image/svg+xml',
        'tif' => 'image/tiff',
        'tiff' => 'image/tiff',
        'ico' => 'image/vnd.microsoft.icon',
        'webp' => 'image/webp',
        'bmp' => 'image/bmp',
        'otf' => 'font/otf',
        'ttf' => 'font/ttf',
        'woff' => 'font/woff',
        'woff2' => 'font/woff2',
        'atom' => 'application/atom+xml',
        'mpd' => 'application/dash+xml',
        'epub' => 'application/epub+zip',
        'geojson' => 'application/geo+json',
        'gz' => 'application/gzip',
        'tgz' => 'application/gzip',
        'jar' => 'application/java-archive',
        'war' => 'application/java-archive',
        'ear' => 'application/java-archive',
        'json' => 'application/json',
        'map' => 'application/json',
        'jsonld' => 'application/ld+json',
        'webmanifest' => 'application/manifest+json',
        'doc' => 'application/msword',
        'ogx' => 'application/ogg',
        'pdf' => 'application/pdf',
        'ps' => 'application/postscript',
        'eps' => 'application/postscript',
        'ai' => 'application/postscript',
        'rss' => 'application/rss+xml',
        'rtf' => 'application/rtf',
        'toml' => 'application/toml',
        'm3u8' => 'application/vnd.apple.mpegurl',
        'kml' => 'application/vnd.google-earth.kml+xml',
        'kmz' => 'application/vnd.google-earth.kmz',
        'xls' => 'application/vnd.ms-excel',
        'ppt' => 'application/vnd.ms-powerpoint',
        'odg' => 'application/vnd.oasis.opendocument.graphics',
        'odp' => 'application/vnd.oasis.opendocument.presentation',
        'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
        'odt' => 'application/vnd.oasis.opendocument.text',
        'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'rar' => 'application/vnd.rar',
        'wasm' => 'application/wasm',
        'xml' => 'application/xml',
        'xsd' => 'application/xml',
        'xsl' => 'application/xslt+xml',
        'xslt' => 'application/xslt+xml',
        '7z' => 'application/x-7z-compressed',
        'bz' => 'application/x-bzip',
        'bz2' => 'application/x-bzip2',
        'run' => 'application/x-makeself',
        'pl' => 'application/x-perl',
        'pm' => 'application/x-perl',
        'rpm' => 'application/x-redhat-package-manager',
        'tar' => 'application/x-tar',
        'tcl' => 'application/x-tcl',
        'tk' => 'application/x-tcl',
        'der' => 'application/x-x509-ca-cert',
        'pem' => 'application/x-x509-ca-cert',
        'crt' => 'application/x-x509-ca-cert',
        'xpi' => 'application/x-xpinstall',
        'xz' => 'application/x-xz',
        'xhtml' => 'application/xhtml+xml',
        'yaml' => 'application/yaml',
        'yml' => 'application/yaml',
        'zip' => 'application/zip',
        'zst' => 'application/zstd',
        'aac' => 'audio/aac',
        'flac' => 'audio/flac',
        'mid' => 'audio/midi',
        'midi' => 'audio/midi',
        'm4a' => 'audio/mp4',
        'mp3' => 'audio/mpeg',
        'oga' => 'audio/ogg',
        'ogg' => 'audio/ogg',
        'opus' => 'audio/ogg',
        'wav' => 'audio/wav',
        'weba' => 'audio/webm',
        '3gpp' => 'video/3gpp',
        '3gp' => 'video/3gpp',
        '3g2' => 'video/3gpp2',
        'ts' => 'video/mp2t',
        'm4v' => 'video/mp4',
        'mp4' => 'video/mp4',
        'mpeg' => 'video/mpeg',
        'mpg' => 'video/mpeg',
        'ogv' => 'video/ogg',
        'mov' => 'video/quicktime',
        'webm' => 'video/webm',
        'asf' => 'video/x-ms-asf',
        'wmv' => 'video/x-ms-wmv',
        'avi' => 'video/x-msvideo',
        'glb' => 'model/gltf-binary',
        'gltf' => 'model/gltf+json',
    ];

    private function __construct()
    {
    }

    public static function lookupMimeTypeFromPath(string $path): string
    {
        return self::lookupMimeTypeFromExtension(\pathinfo($path, PATHINFO_EXTENSION));
    }

    public static function lookupMimeTypeFromExtension(string $extension): string
    {
        return self::MIME_TYPES_MAP[\strtolower($extension)] ?? 'application/octet-stream';
    }
}
