name: Tests

on:
  push:
  pull_request:

jobs:
  codestyle:
    runs-on: ubuntu-latest
    name: Codestyle
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: posix, pcntl
          tools: composer:v2

      - name: Composer install
        run: composer install

      - name: Monorepo validate
        run: composer run monorepo-validate

      - name: Codestyle check
        run: composer run cs

      - name: Static analyze
        run: composer run psalm

  tests:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        php: [ '8.2', '8.3', '8.4' ]
    runs-on: ${{ matrix.os }}
    name: Tests - ${{ matrix.os }}/PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: posix, pcntl
          tools: composer:v2

      - name: Composer install
        run: composer install

      - name: Tests
        run: composer run test
